import type { z } from "zod";
import type { FeatureGate, SchemaEntry } from "./types";
import { typeToSchema, type SchemaField } from "./schema";

export interface EnvokerConfigFile {
  schema: Record<string, SchemaEntry>;
  profile?: string;
  profiles?: Record<string, Record<string, SchemaEntry>>;
  features?: Record<string, FeatureGate>;
}

export async function loadConfig(path?: string): Promise<EnvokerConfigFile> {
  const searchPaths = path ? [path] : [".envokerrc.json", "envoker.config.json"];

  for (const searchPath of searchPaths) {
    const file = Bun.file(searchPath);
    const exists = await file.exists();
    if (exists) {
      const text = await file.text();
      try {
        const parsed = JSON.parse(text);

        if (!parsed.schema || typeof parsed.schema !== "object") {
          throw new Error(`Config file "${searchPath}" must have a "schema" field`);
        }

        const config: EnvokerConfigFile = { schema: parsed.schema };

        if (parsed.profiles) {
          config.profiles = parsed.profiles;
        }

        if (parsed.features) {
          config.features = parsed.features;
        }

        return config;
      } catch (err) {
        if (err instanceof SyntaxError) {
          throw new Error(`Invalid JSON in config file "${searchPath}": ${err.message}`);
        }
        throw err;
      }
    }
  }

  throw new Error(
    path
      ? `Config file not found: ${path}`
      : "No config file found. Create a .envokerrc.json or pass --config <path>"
  );
}

export function generateEnvExample(config: EnvokerConfigFile, activeProfile?: string): string {
  const lines: string[] = [];
  lines.push("# Environment Variables");
  lines.push(`# Generated by envoker`);
  lines.push(`# Profile: ${activeProfile ?? "default"}`);
  lines.push("");

  const mergedSchema = { ...config.schema };

  if (activeProfile && config.profiles?.[activeProfile]) {
    Object.assign(mergedSchema, config.profiles[activeProfile]);
  }

  for (const [key, entry] of Object.entries(mergedSchema)) {
    if (entry.description) {
      lines.push(`# ${entry.description}`);
    }

    const isField = "type" in entry;
    const isSchema = "schema" in entry;

    if (isField) {
      const field = entry as {
        type: string;
        required?: boolean;
        default?: unknown;
        values?: readonly string[];
        secret?: boolean;
      };
      const typeInfo = field.values ? `${field.type} (${field.values.join(" | ")})` : field.type;
      lines.push(`# Type: ${typeInfo}`);
      if (field.required !== false) {
        lines.push(`# Required: yes`);
      } else {
        lines.push(`# Required: no`);
      }
      if (field.default !== undefined) {
        lines.push(`# Default: ${field.default}`);
      }
      if (field.secret) {
        lines.push(`# Secret: yes`);
      }

      if (field.default !== undefined) {
        lines.push(`${key}=${field.default}`);
      } else {
        lines.push(`# ${key}=`);
      }
    } else if (isSchema) {
      const sEntry = entry as { required?: boolean; secret?: boolean; description?: string };
      if (sEntry.required !== false) {
        lines.push(`# Required: yes`);
      } else {
        lines.push(`# Required: no`);
      }
      if (sEntry.secret) {
        lines.push(`# Secret: yes`);
      }
      lines.push(`# ${key}=`);
    } else {
      lines.push(`# ${key}=`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

const SECRET_CENSOR = "[REDACTED]";

export async function runCheck(
  config: EnvokerConfigFile,
  activeProfile?: string
): Promise<{
  results: Array<{ key: string; status: "ok" | "missing" | "invalid"; message: string }>;
  errors: Array<{ key: string; message: string }>;
}> {
  const results: Array<{ key: string; status: "ok" | "missing" | "invalid"; message: string }> = [];
  const errors: Array<{ key: string; message: string }> = [];

  const mergedSchema = { ...config.schema };
  if (activeProfile && config.profiles?.[activeProfile]) {
    Object.assign(mergedSchema, config.profiles[activeProfile]);
  }

  for (const [key, entry] of Object.entries(mergedSchema)) {
    const raw = process.env[key];
    const isField = "type" in entry;

    let required = true;
    let hasDefault = false;

    if (isField) {
      const field = entry as { required?: boolean; default?: unknown };
      required = field.required !== false;
      hasDefault = field.default !== undefined;
    } else if ("schema" in entry) {
      const f = entry as { required?: boolean; schema: z.ZodType<unknown> };
      required = f.required !== false;
      hasDefault = f.schema.safeParse(undefined).success;
    }

    if (raw === undefined || raw === "") {
      if (hasDefault) {
        results.push({ key, status: "ok", message: "Using default value" });
      } else if (!required) {
        results.push({ key, status: "ok", message: "Optional, not set" });
      } else {
        results.push({ key, status: "missing", message: "Not set" });
        errors.push({ key, message: "Missing required environment variable" });
      }
      continue;
    }

    const isSecret = (entry as { secret?: boolean }).secret ?? false;
    const display = isSecret ? SECRET_CENSOR : raw;

    try {
      if (isField) {
        const schema = typeToSchema(entry as SchemaField);
        schema.parse(raw);
      } else if ("schema" in entry) {
        const f = entry as { schema: z.ZodType<unknown> };
        f.schema.parse(raw);
      }
      results.push({
        key,
        status: "ok",
        message: `Set (${display.length > 25 ? display.substring(0, 25) + "..." : display})`,
      });
    } catch {
      results.push({ key, status: "invalid", message: `Invalid: "${display}"` });
      errors.push({ key, message: `Invalid value: ${display}` });
    }
  }

  return { results, errors };
}
