import { z } from "zod";
import type { SchemaEntry } from "./types";

export interface BeaconConfigFile {
  schema: Record<string, SchemaEntry>;
  profile?: string;
  profiles?: Record<string, Record<string, SchemaEntry>>;
}

export async function loadConfig(path?: string): Promise<BeaconConfigFile> {
  const searchPaths = path ? [path] : [".beaconrc.json", "beacon.config.json"];

  for (const searchPath of searchPaths) {
    const file = Bun.file(searchPath);
    const exists = await file.exists();
    if (exists) {
      const text = await file.text();
      try {
        const parsed = JSON.parse(text);

        if (!parsed.schema || typeof parsed.schema !== "object") {
          throw new Error(`Config file "${searchPath}" must have a "schema" field`);
        }

        const config: BeaconConfigFile = { schema: parsed.schema };

        if (parsed.profiles) {
          config.profiles = parsed.profiles;
        }

        return config;
      } catch (err) {
        if (err instanceof SyntaxError) {
          throw new Error(`Invalid JSON in config file "${searchPath}": ${err.message}`);
        }
        throw err;
      }
    }
  }

  throw new Error(
    path
      ? `Config file not found: ${path}`
      : "No config file found. Create a .beaconrc.json or pass --config <path>"
  );
}

export function generateEnvExample(config: BeaconConfigFile, activeProfile?: string): string {
  const lines: string[] = [];
  lines.push("# Environment Variables");
  lines.push(`# Generated by @joinremba/beacon`);
  lines.push(`# Profile: ${activeProfile ?? "default"}`);
  lines.push("");

  const mergedSchema = { ...config.schema };

  if (activeProfile && config.profiles?.[activeProfile]) {
    Object.assign(mergedSchema, config.profiles[activeProfile]);
  }

  for (const [key, entry] of Object.entries(mergedSchema)) {
    if (entry.description) {
      lines.push(`# ${entry.description}`);
    }

    const isField = "type" in entry;
    const isSchema = "schema" in entry;

    if (isField) {
      const field = entry as {
        type: string;
        required?: boolean;
        default?: unknown;
        values?: readonly string[];
        secret?: boolean;
      };
      const typeInfo = field.values ? `${field.type} (${field.values.join(" | ")})` : field.type;
      lines.push(`# Type: ${typeInfo}`);
      if (field.required !== false) {
        lines.push(`# Required: yes`);
      } else {
        lines.push(`# Required: no`);
      }
      if (field.default !== undefined) {
        lines.push(`# Default: ${field.default}`);
      }
      if (field.secret) {
        lines.push(`# Secret: yes`);
      }

      if (field.default !== undefined) {
        lines.push(`${key}=${field.default}`);
      } else {
        lines.push(`# ${key}=`);
      }
    } else if (isSchema) {
      const sEntry = entry as { required?: boolean; secret?: boolean; description?: string };
      if (sEntry.required !== false) {
        lines.push(`# Required: yes`);
      } else {
        lines.push(`# Required: no`);
      }
      if (sEntry.secret) {
        lines.push(`# Secret: yes`);
      }
      lines.push(`# ${key}=`);
    } else {
      lines.push(`# ${key}=`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

const typeToSchema = (entry: Record<string, unknown>): z.ZodType<unknown> => {
  const type = entry.type as string;
  let base: z.ZodType<unknown>;

  switch (type) {
    case "string":
    case "host":
      base = z.string();
      break;
    case "url":
      base = z.string().url();
      break;
    case "number":
      base = z.coerce.number();
      break;
    case "integer":
      base = z.coerce.number().int();
      break;
    case "boolean":
      base = z
        .string()
        .transform((v) => v === "true" || v === "1")
        .pipe(z.boolean());
      break;
    case "enum":
      base = z.enum((entry.values ?? []) as unknown as [string, ...string[]]);
      break;
    case "port":
      base = z.coerce.number().int().min(1).max(65535);
      break;
    case "email":
      base = z.string().email();
      break;
    default:
      base = z.string();
  }

  if (entry.default !== undefined) {
    base = base.default(entry.default as string | number | boolean);
  }

  return base;
};

export async function runCheck(
  config: BeaconConfigFile,
  activeProfile?: string
): Promise<{
  results: Array<{ key: string; status: "ok" | "missing" | "invalid"; message: string }>;
  errors: Array<{ key: string; message: string }>;
}> {
  const results: Array<{ key: string; status: "ok" | "missing" | "invalid"; message: string }> = [];
  const errors: Array<{ key: string; message: string }> = [];

  const mergedSchema = { ...config.schema };
  if (activeProfile && config.profiles?.[activeProfile]) {
    Object.assign(mergedSchema, config.profiles[activeProfile]);
  }

  for (const [key, entry] of Object.entries(mergedSchema)) {
    const raw = process.env[key];
    const isField = "type" in entry;

    let required = true;
    let hasDefault = false;

    if (isField) {
      const field = entry as { required?: boolean; default?: unknown };
      required = field.required !== false;
      hasDefault = field.default !== undefined;
    } else {
      const f = entry as { required?: boolean };
      required = f.required !== false;
    }

    if (raw === undefined || raw === "") {
      if (hasDefault) {
        results.push({ key, status: "ok", message: "Using default value" });
      } else if (!required) {
        results.push({ key, status: "ok", message: "Optional, not set" });
      } else {
        results.push({ key, status: "missing", message: "Not set" });
        errors.push({ key, message: "Missing required environment variable" });
      }
      continue;
    }

    try {
      if (isField) {
        const schema = typeToSchema(entry as unknown as Record<string, unknown>);
        schema.parse(raw);
      }
      results.push({
        key,
        status: "ok",
        message: `Set (${raw.length > 25 ? raw.substring(0, 25) + "..." : raw})`,
      });
    } catch {
      results.push({ key, status: "invalid", message: `Invalid: "${raw}"` });
      errors.push({ key, message: `Invalid value: ${raw}` });
    }
  }

  return { results, errors };
}
